#set heading(numbering: "1.")
#show link: underline

#align(center, text(30pt)[*Чифир (Chifir) Engine*])
#align(center, text(20pt)[Copyright 2025 Randomcode Developers])

#outline()
#pagebreak()

#include("intro.typ")
#pagebreak()
#include("components.typ")
#pagebreak()
#include("platforms.typ")
#pagebreak()
#include("libraries.typ")
#pagebreak()
#include("style.typ")
#pagebreak()
#include("tools.typ")
#pagebreak()
#include("scene.typ")
#pagebreak()
#include("renderer.typ")
#pagebreak()
