# This file is used by gatherlicenses.py to make a zip/folder that has all the licenses

[d3d12_agility]
name = "DirectX 12 Agility SDK"
author = "Microsoft"
use = "DirectX 12 runtime"
path = "external/d3d12_agility"
license = "external/d3d12_agility/LICENSE.txt"
url = "https://devblogs.microsoft.com/directx/directx12agility"

[directx]
name = "DirectX Headers"
author = "Microsoft"
use = "DirectX 12 interfaces"
path = "external/directx12"
license = "external/directx/LICENSE"
url = "https://github.com/Microsoft/DirectX-Headers"

[musl]
name = "musl"
author = "Rich Felker, et al."
use = "Some time code borrowed"
path = "base/platform_unix.cpp"
license = "external/musl.txt"
url = "https://git.musl-libc.org/cgit/musl"

[phnt]
name = "phnt"
author = "Winsider Seminars & Solutions, Inc."
use = "Accessing internal Windows APIs"
path = "external/phnt"
license = "external/phnt/LICENSE"
url = "https://github.com/winsiderss/phnt"

[sdl3]
name = "SDL3"
author = "Sam Latinga"
use = "Some 32-bit arithmetic code borrowed"
path = "public/base/compiler_msvc_x86.asm"
license = "external/sdl3.txt"
url = "https://libsdl.org"

[stb]
name = "stb"
author = "Sean Barrett (nothings)"
use = "Mainly sprintf"
path = "external/stb"
license = "external/stb/LICENSE"
url = "https://github.com/nothings/stb"

[volk]
name = "volk"
author = "Arseny Kapoulkine (zeux)"
use = "Vulkan loading"
path = "external/volk"
license = "external/volk/LICENSE.md"
url = "https://github.com/zeux/volk"

[vulkan]
name = "Vulkan Headers"
author = "Khronos Group"
use = "Vulkan declarations"
path = "external/vulkan"
license = "external/vulkan/LICENSE.md"
url = "https://github.com/Khronos-Group/Vulkan-Headers"
