[musl]
name = "musl"
author = "Rich Felker, et al."
path = "https://git.musl-libc.org/cgit/musl"
license = "external/musl.txt"

[phnt]
name = "phnt"
author = "Winsider Seminars & Solutions, Inc."
path = "external/phnt"
license = "external/phnt/LICENSE"

[stb]
name = "stb"
author = "Sean Barrett"
path = "external/stb"
license = "external/stb/LICENSE"
