[musl]
name = "musl"
author = "Rich Felker, et al."
use = "Some time code borrowed"
path = "https://git.musl-libc.org/cgit/musl"
license = "external/musl.txt"
url = "https://git.musl-libc.org/cgit/musl"

[directx]
name = "DirectX Headers"
author = "Microsoft"
use = "DirectX 12 interfaces"
path = "external/directx12"
license = "external/directx/LICENSE"
url = "https://github.com/Microsoft/DirectX-Headers"

[phnt]
name = "phnt"
author = "Winsider Seminars & Solutions, Inc."
use = "Accessing internal Windows APIs"
path = "external/phnt"
license = "external/phnt/LICENSE"
url = "https://github.com/winsiderss/phnt"

[stb]
name = "stb"
author = "Sean Barrett (nothings)"
use = "Mainly sprintf"
path = "external/stb"
license = "external/stb/LICENSE"
url = "https://github.com/nothings/stb"

[volk]
name = "volk"
author = "Arseny Kapoulkine (zeux)"
use = "Vulkan loading"
path = "external/volk"
license = "external/volk/LICENSE.md"
url = "https://github.com/zeux/volk"

[vulkan]
name = "Vulkan Headers"
author = "Khronos Group"
use = "Vulkan declarations"
path = "external/vulkan"
license = "external/vulkan/LICENSE.md"
url = "https://github.com/Khronos-Group/Vulkan-Headers"
